name: moiselin_cloud_app
description: "Aplicacion para la gestion de tu propia nube"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  chewie: ^1.7.1
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  dio: ^5.0.0
  path_provider: ^2.0.0
  gallery_saver_plus: ^3.0.0
  permission_handler: ^11.3.1
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  intl: ^0.20.2 
  wechat_assets_picker: ^9.0.0
  photo_manager: ^3.0.0
  flutter_localizations:
    sdk: flutter
  file_picker: ^10.3.10
  flutter_secure_storage: ^10.0.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true